### ISSUE TITLE
Dodanie do formularza opcji umieszczenia stopki

### ISSUE THREAD

**Issue by feliksczart** [przemekxa/BootstrapBuilder#13]
o pełny kod strony HTML
o kod zawiera tagi dołączające Bootstrapa (CDN)
o kod zawiera tag "main" (z klasą "container") w sekcji "body"
o strona zawiera stopkę na dole strony

**Comment by przemekxa** [comment]
Zrobione: e7914cfec336a78ad7ac60d5a045b532a03f343e
