### ISSUE TITLE
Dodanie do formularza różnych opcji nagłówka - static lub fixed

### ISSUE THREAD

**Issue by piter104** [przemekxa/BootstrapBuilder#15]
o pełny kod strony HTML
o kod zawiera tagi dołączające Bootstrapa (CDN)
o kod zawiera tag "main" (z klasą "container") w sekcji "body"
o strona zawiera nagłówek, który nie podąża za użytkownikiem podczas przewijania ("static") lub podąża ("fixed")

**Comment by przemekxa** [comment]
Zrobione: e7914cfec336a78ad7ac60d5a045b532a03f343e
